version: "3.3"
services:
    idb:
        image: postgres:11.2-alpine
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: backend
        volumes:
            - ../pgdata:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        healthcheck:
            test: exit 0
